#!/usr/bin/env node

/**
 * Simple script to generate data.js from JSON files
 * 
 * This script reads JSON files from assets/data/ and generates
 * JavaScript export statements for inclusion in data.js.
 * 
 * For a solo dev, this keeps things simple: edit JSON files, run this script.
 * 
 * Usage: node scripts/generate-data.js
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../assets/data');
const OUTPUT_FILE = path.join(__dirname, '../assets/js/character-sheet/data.json-exports.js');

// Map of JSON files to export names
const JSON_EXPORTS = {
    'xpLevels.json': 'xpLevels',
    'permanentBonuses.json': 'permanentBonuses',
    'atmosphericBuffs.json': 'atmosphericBuffs'
};

function generateExports() {
    let exports = '/**\n';
    exports += ' * Auto-generated exports from JSON files\n';
    exports += ' * DO NOT EDIT THIS FILE DIRECTLY\n';
    exports += ' * Run: node scripts/generate-data.js\n';
    exports += ' */\n\n';
    
    const loadedData = {};
    
    for (const [filename, exportName] of Object.entries(JSON_EXPORTS)) {
        const filePath = path.join(DATA_DIR, filename);
        
        if (!fs.existsSync(filePath)) {
            console.warn(`Warning: ${filename} not found, skipping...`);
            continue;
        }
        
        try {
            const jsonContent = fs.readFileSync(filePath, 'utf8');
            const data = JSON.parse(jsonContent);
            loadedData[exportName] = data;
            
            // Format the export statement
            // For xpLevels, preserve numeric keys when possible
            if (exportName === 'xpLevels') {
                // Convert to object with numeric keys
                const numericData = {};
                for (const key in data) {
                    const numKey = parseInt(key);
                    numericData[isNaN(numKey) ? key : numKey] = data[key];
                }
                exports += `export const ${exportName} = ${JSON.stringify(numericData, null, 4).replace(/"(\d+)":/g, '$1:')};\n\n`;
            } else {
                exports += `export const ${exportName} = ${JSON.stringify(data, null, 4)};\n\n`;
            }
        } catch (error) {
            console.error(`Error processing ${filename}:`, error.message);
            process.exit(1);
        }
    }
    
    // Write the generated file
    fs.writeFileSync(OUTPUT_FILE, exports, 'utf8');
    console.log(`✓ Generated ${OUTPUT_FILE}`);
    console.log(`  Exported: ${Object.keys(loadedData).join(', ')}`);
}

// Run the script
if (require.main === module) {
    generateExports();
}

module.exports = { generateExports };

